apiVersion: v1
kind: Service
metadata:
  labels:
    v1alpha1.mysql.oracle.com/cluster: yu-cluster
  name: yu-cluster-name-rw
spec:
  clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    v1alpha1.mysql.oracle.com/cluster: yu-cluster
    v1alpha1.mysql.oracle.com/role: primary
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    v1alpha1.mysql.oracle.com/cluster: yu-cluster
  name: yu-cluster-name-ro
spec:
  clusterIP: None
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    v1alpha1.mysql.oracle.com/cluster: yu-cluster
    v1alpha1.mysql.oracle.com/role: secondary
  type: ClusterIP