---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kais-demo1
  namespace: kais-namespace
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kais-demo1
  namespace: kais-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kais-demo1
subjects:
- kind: ServiceAccount
  name: kais-demo1
  namespace: kais-namespace