apiVersion: v1
kind: Service
metadata:
  name: r-demo
  labels:
    app: r-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    app: r-demo
